/*
 * This file is generated by jOOQ.
 */
package io.github.suppierk.test.example;

import io.github.suppierk.test.example.tables.TestTable;
import io.github.suppierk.test.example.tables.records.TestTableRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/** A class modelling foreign key relationships and constraints of tables in public. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<TestTableRecord> TEST_PKEY =
      Internal.createUniqueKey(
          TestTable.TEST_TABLE,
          DSL.name("test_pkey"),
          new TableField[] {TestTable.TEST_TABLE.ID},
          true);
}
