/*
 * This file is generated by jOOQ.
 */
package io.github.suppierk.test.example;

import io.github.suppierk.test.example.tables.TestTable;

/** Convenience access to all tables in public. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

  /** The table <code>public.test</code>. */
  public static final TestTable TEST_TABLE = TestTable.TEST_TABLE;
}
